### ISSUE TITLE
API key is visible in code

### ISSUE THREAD

**Issue by Saurabh-Daware** [darshjain/covid-tracker#1]
Your API keys are visible [here](https://github.com/darshjain/covid-tracker/blob/9679e969d1f619bddaf9d7f44314d8e733acc35d/covidapp/views.py#L7).
You should hide your API keys in the .env file **or** use an API like [Disease.sh](https://www.disease.sh).

**Comment by ameybh** [comment]
@darshjain This can be closed now.

**Comment by darshjain** [comment]
Its solved closing
